#!/bin/sh
set -e
if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    systemctl stop hermitshell-ui hermitshell-agent 2>/dev/null || true
    systemctl disable hermitshell-ui hermitshell-agent 2>/dev/null || true
fi
